apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maas-models
resources:
  - llminferenceservice.yaml
  - maasmodelref.yaml
configMapGenerator:
  - name: gemma-3-270m-it-chat-template
    files:
      - chat-template-playground.jinja
    options:
      disableNameSuffixHash: true
      labels:
        opendatahub.io/dashboard: "true"
